# Generated by Django 4.0.3 on 2022-03-26 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competicao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time1', models.CharField(max_length=100, verbose_name='Time1')),
                ('time2', models.CharField(max_length=100, verbose_name='Time2')),
                ('resultado1', models.IntegerField(verbose_name='Resultado1')),
                ('resultado2', models.IntegerField(verbose_name='Resultado2')),
            ],
        ),
        migrations.DeleteModel(
            name='Time',
        ),
    ]
