# Generated by Django 4.0.3 on 2022-03-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competicao', '0002_competicao_delete_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('pontos', models.IntegerField(verbose_name='Pontos')),
            ],
        ),
    ]
