# Generated by Django 4.0.3 on 2022-03-26 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competicao', '0004_alter_time_pontos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Competicao',
        ),
        migrations.RenameField(
            model_name='time',
            old_name='pontos',
            new_name='gols',
        ),
    ]
