# Generated by Django 4.0.3 on 2022-03-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competicao', '0006_remove_time_nome_alter_time_gols_alter_time_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='nome',
            field=models.CharField(default=0, max_length=100, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='time',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
