# Generated by Django 4.0.3 on 2022-03-26 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competicao', '0008_disputa_resultado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disputa',
            name='times',
        ),
        migrations.AddField(
            model_name='disputa',
            name='time01',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='time01', to='competicao.time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disputa',
            name='time02',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='time02', to='competicao.time'),
            preserve_default=False,
        ),
    ]
