# Generated by Django 4.0.3 on 2022-03-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competicao', '0010_resultado_gols'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultado',
            name='gols',
        ),
        migrations.AddField(
            model_name='resultado',
            name='gols',
            field=models.ManyToManyField(to='competicao.time'),
        ),
    ]
