# Generated by Django 4.0.3 on 2022-03-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competicao', '0012_alter_resultado_gols'),
    ]

    operations = [
        migrations.AddField(
            model_name='disputa',
            name='gols01',
            field=models.IntegerField(default=0, verbose_name='Gols01'),
        ),
        migrations.AddField(
            model_name='disputa',
            name='gols02',
            field=models.IntegerField(default=0, verbose_name='Gols02'),
        ),
    ]
