# Generated by Django 4.0.3 on 2022-03-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competicao', '0013_disputa_gols01_disputa_gols02'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disputa',
            name='data',
            field=models.DateTimeField(verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='disputa',
            name='gols01',
            field=models.IntegerField(default=0, verbose_name='gols01'),
        ),
        migrations.AlterField(
            model_name='disputa',
            name='gols02',
            field=models.IntegerField(default=0, verbose_name='gols02'),
        ),
        migrations.AlterField(
            model_name='disputa',
            name='horario',
            field=models.TimeField(verbose_name='hora'),
        ),
        migrations.AlterField(
            model_name='disputa',
            name='local',
            field=models.CharField(max_length=100, verbose_name='local'),
        ),
    ]
