# Generated by Django 4.0.3 on 2022-03-26 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competicao', '0014_alter_disputa_data_alter_disputa_gols01_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='gols',
        ),
        migrations.DeleteModel(
            name='Resultado',
        ),
    ]
